name: Build and package iPXE

on:
  push:
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: noninteractive
  IPXE_COMMIT: "4fa4052c7ebb59e4d4aa396f1563c89118623ec7"
  IPXE_VERSION: "1.21.1"
  PACKAGE_VERSION: "1"
  TRUST_LIST: "../../ComodoAAA.pem,../../USERTrust_RSA_selfsigned.pem"
  EMBED_LIST: "../../boot.ipxe"
  BUILD_TARGETS:
    bin-x86_64-efi/ipxe.efi
    bin-x86_64-efi/snp.efi
    bin-x86_64-efi/snponly.efi
    bin-x86_64-efi/ipxe.usb
    bin-x86_64-pcbios/ipxe.lkrn
    bin-x86_64-pcbios/undionly.kpxe

jobs:
  build-ipxe:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y isolinux genisoimage sbsigntool mtools syslinux
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkout iPXE
        uses: actions/checkout@v3
        with:
          repository: ipxe/ipxe
          ref: ${{ env.IPXE_COMMIT }}
          path: src/ipxe
          fetch-depth: 0
      - name: Install custom config files
        working-directory: src/ipxe/src
        run: |
          cp ../../general.h config/local/general.h
          cp ../../console.h config/local/console.h
          cp ../../branding.h config/local/branding.h
      - name: build ipxe
        working-directory: src/ipxe/src
        run: make -j8 $BUILD_TARGETS CERT="$TRUST_LIST" TRUST="$TRUST_LIST" EMBED="$EMBED_LIST"
      - name: postprocess efi binary
        working-directory: src/ipxe/src
        run: |
          chmod +x bin-x86_64-efi/ipxe.efi
          sbsign --key <(echo "${{ secrets.SECUREBOOT_KEY }}") --cert <(echo "${{ secrets.SECUREBOOT_CRT }}") --output bin-x86_64-efi/ipxe.efi bin-x86_64-efi/ipxe.efi
      - name: build iso image
        working-directory: src/ipxe/src
        run: ./util/genfsimg -o ipxe.iso bin-x86_64-pcbios/ipxe.lkrn bin-x86_64-efi/ipxe.efi
      - name: copy artifacts to central path
        working-directory: src/ipxe/src
        run: |
          mkdir ../../../artifacts
          cp $BUILD_TARGETS ../../../artifacts
          cp ipxe.iso ../../../artifacts
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ipxe-build
          path: artifacts
